name: deep_dem
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
 - rasterio
 - shapely
 - geopandas
 - matplotlib
 - numpy=1.26.4
 - python-pdal==3.3.0
 - pdal
 - pytorch
 - pytorch-cuda=11.8
 - torchgeo
 - pytorch-lightning
 - jupyterlab
 - tensorboard
 - smp
 - tqdm
 - ipyleaflet
 - scikit-build
 - scikit-image
 - earthaccess