name: der
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  # Python basics
  - pip

  # ResDepth dependencies
  - numpy
  - scipy
  - easydict
  - pytorch
  - pytorch-cuda  # needed for GPU, remove for Mac
  - torchvision
  - tensorboard
  
  # NN data ingestion and training
  - torchgeo>=0.3.1
  - pytorch-lightning
  
  # Development tools
  - jupyterlab

  # Dataset visualization tools
  - matplotlib
  - matplotlib-scalebar
  - streamlit
  - folium

  # Raster and point cloud handling
  - shapely
  - rasterio
  - rioxarray
  - pdal
  - python-pdal
  - gdal
  - scikit-image
  - geopandas
  - astropy

  - pip:
    - black # code formatting
    - torchsummary # obsolete, but needed by ResDepth

# TODO Ames Stereo Pipeline is not included

# TODO careful when using dshean/uw-cryo packages (not specified here)
# Initial dataset script expects these tools in PATH
# - pygeotools # only used in tile prep, may remove
# - demcoreg # dem_mask.py useful to mask point cloud
# - gdal_tools
# - more???
